import { inter } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'TR Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'font-inter antialiased bg-slate-100 text-slate-900',
          inter.variable,
        )}
      >
        {children}
      </body>
    </html>
  )
}
